name: Java CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_BACKEND: yourdockerhubusername/taskmanager-backend
  IMAGE_FRONTEND: yourdockerhubusername/taskmanager-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # ===== BACKEND BUILD =====
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build Spring Boot App
      run: |
        cd backend
        chmod +x mvnw
        ./mvnw clean install -DskipTests

    # ===== FRONTEND BUILD =====
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Build React App
      run: |
        cd frontend
        npm install
        npm run build

    # ===== DOCKER LOGIN =====
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ===== BUILD & PUSH BACKEND IMAGE =====
    - name: Docker Build & Push Backend
      run: |
        docker build -f Dockerfile.backend -t $IMAGE_BACKEND:latest .
        docker push $IMAGE_BACKEND:latest

    # ===== BUILD & PUSH FRONTEND IMAGE =====
    - name: Docker Build & Push Frontend
      run: |
        docker build -f Dockerfile.frontend -t $IMAGE_FRONTEND:latest .
        docker push $IMAGE_FRONTEND:latest
