name: Fullstack CI/CD Pipeline

on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_BACKEND: guruvenkatesh03/taskmanager-backend
  IMAGE_FRONTEND: guruvenkatesh03/taskmanager-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up Java for Spring Boot backend
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Step 3: Build Spring Boot application
    - name: Build Spring Boot App
      run: |
        cd backend
        chmod +x mvnw
        ./mvnw clean install -DskipTests

    # Step 4: Set up Node.js for React frontend
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    # Step 5: Build React frontend
    - name: Build React App
      run: |
        cd frontend
        npm install
        npm run build

    # Step 6: Login to Docker Hub
    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 7: Build and push backend Docker image
    - name: Docker Build & Push Backend
      run: |
        docker build -f Dockerfile.backend -t $IMAGE_BACKEND:latest .
        docker push $IMAGE_BACKEND:latest

    # Step 8: Build and push frontend Docker image
    - name: Docker Build & Push Frontend
      run: |
        docker build -f Dockerfile.frontend -t $IMAGE_FRONTEND:latest .
        docker push $IMAGE_FRONTEND:latest
